version: '3.7'

services:
  mysql_service:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      app_network:
        ipv4_address: 172.28.1.2

  flask_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql_service:
        condition: service_started
    networks:
      app_network:
        ipv4_address: 172.28.1.1

networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
